[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "nginx"]

[phases.install]
cmds = ["composer install --ignore-platform-reqs --no-dev --optimize-autoloader"]

# DELETE THE WHOLE [start] BLOCK THAT WAS HERE