[phases.setup]
nixPkgs = ["php82", "php82Packages.composer"]
nixLibs = ["phpExtensions.pgsql"]

[phases.install]
cmds = [
  "composer install --ignore-platform-reqs --no-dev --optimize-autoloader"
]

[start]
cmd = "php artisan reverb:start --host=0.0.0.0 --port=8081 --debug"