[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "nodejs_20", "nginx"]

[phases.install]
cmds = [
  "composer install --ignore-platform-reqs --no-dev --optimize-autoloader",
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache"
]